### ISSUE TITLE
Remove opacity from qibolab's schemes

### ISSUE THREAD

**Issue by MatteoRobbiati** [qiboteam/xmind-diagrams#5]
It can be useful to have schemes without opacity to be rendered properly in light/dark mode if used in the docs.

**Comment by scarrazza** [comment]
I fully agree, in particular we are already using some of them: https://github.com/qiboteam/qibolab/pull/546/files#diff-f29b87844752fef436af68fcd3c97e6dba2e4d703f23dd44eb71406538702ab9
